site_name: Rare Disease Project Documentation
theme: readthedocs
nav:
  - index.md
  - installation.md
  - customization.md
  - service-accounts.md
  - deployment.md
  - migration.md
  - api.md
  - release-notes.md
plugins:
  - macros
extra:
  rdp_version: 1.4.11
  git_ref: support-1.4
